# Generated by Django 5.0.2 on 2024-02-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_user_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin_code',
            field=models.CharField(default='0000', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('waiting_for_scan', 'Ожидание сканирования лица'), ('waiting_for_pin', 'Ожидание ввода пин-кода'), ('payment_confirmed', 'Оплата подтверждена')], default='waiting_for_scan', max_length=40),
        ),
    ]
